name: Code Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 깃 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. EC2 서버를 known_hosts에 추가
      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # 4. real.env 파일 생성
      - name: Create real.env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> real.env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> real.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> real.env
          echo "DB_PW=${{ secrets.DB_PW }}" >> real.env

      # 5. 프로젝트(백엔드) 파일을 원격 서버로 복사
      - name: Copy project files to remote server
        run: |
          scp -P ${{ secrets.REMOTE_PORT }} \
              -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -r ./* \
              ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}

      # 6. real.env 파일을 원격 서버로 복사
      - name: Copy env file to remote server
        run: |
          scp -P ${{ secrets.REMOTE_PORT }} \
              -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              real.env \
              ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}